# Generated by Django 3.2.6 on 2021-10-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20211006_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
